version: "3.0"
services:
  nginx:
    build: .
    volumes:
      - .nais/dev-gcp/nginx.conf.d:/etc/nginx/conf.d/dev-gcp:ro
      - .nais/dev-fss/nginx.conf.d:/etc/nginx/conf.d/dev-fss:ro
      - .nais/prod-gcp/nginx.conf.d:/etc/nginx/conf.d/prod-gcp:ro
      - .nais/prod-fss/nginx.conf.d:/etc/nginx/conf.d/prod-fss:ro
    networks:
      test:
        aliases:
          - www.nav.no
          - arbeid.dev.nav.no
  test:
    image: "orangeopensource/hurl"
    entrypoint: hurl --test --glob '/tests/*.hurl'
    depends_on:
      - nginx
    volumes:
      - ./tests:/tests:ro
    networks:
      test:

networks:
  test: