apiVersion: v1
kind: ConfigMap
metadata:
  name: dp-videresending-config
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
data:
  prod-fss.conf: |
    server {
      listen       8080;
      server_name  dagpenger-regel-ui.nais.adeo.no;
    
      return 301 $scheme://dagpenger-regel-ui.intern.nav.no$request_uri;
    }
