apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-videresending
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  image: "{{image}}"
  port: 8080
  liveness:
    path: /isalive
  readiness:
    path: /isready
    initialDelay: 5
  prometheus:
    enabled: false
  replicas:
    min: 2
    max: 2
  resources:
    limits:
      memory: 128Mi
    requests:
      cpu: 130m
      memory: 64Mi
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  filesFrom:
    - configmap: dp-videresending-config
      mountPath: /etc/nginx/conf.d/
  observability:
    logging:
      destinations:
        - id: loki
        - id: elastic
    autoInstrumentation:
      enabled: true
      runtime: java
