apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-videresending
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  image: {{image}}
  port: 3000
  liveness:
    path: /isalive
  readiness:
    path: /isready
  prometheus:
    enabled: false
  replicas:
    min: 2
    max: 2
  resources:
    limits:
      cpu: 50m
      memory: 128Mi
    requests:
      cpu: 30m
      memory: 64Mi
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  filesFrom:
    - configmap: dp-videresending-config
      mountPath: /etc/nginx/conf.d/
