ingresses:
  - https://dp-videresending.intern.nav.no
  - https://www.nav.no/arbeid/dagpenger/soknad-veileder
  - https://www.nav.no/arbeid/dagpenger/soknad-innsending
  - https://www.nav.no/arbeid/dagpenger/kalkulator