apiVersion: v1
kind: ConfigMap
metadata:
  name: dp-videresending-config
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
data:
  dev-gcp.conf: |
    server {
      listen       8080;
      server_name  dp-videresending.dev.intern.nav.no;

      location /test {
        return 201 "cool";
      }
    }