name: Build and deploy

on: [ push ]

env:
  IMAGE: ghcr.io/${{ github.repository }}:${{ github.sha }}

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - run: kubectl create configmap --dry-run=client --from-file .nais/dev-fss/nginx.conf.d/ --namespace teamdagpenger dp-foobar -o yaml

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v3
        with:
          tags: ${{ env.IMAGE }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy-dev:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cluster: [ dev-gcp, dev-fss ]
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@master
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: ${{ matrix.cluster }}
          RESOURCE: .nais/nais.yaml,.nais/${{ matrix.cluster }}/nginx.yaml
          VARS: .nais/${{ matrix.cluster }}/ingresses.yaml
          PRINT_PAYLOAD: true

  deploy-prod:
    needs: [ build ]
    if: github.ref == 'refs/heads/mains'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cluster: [ prod-gcp, prod-fss ]
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@master
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: ${{ matrix.cluster }}
          RESOURCE: .nais/nais.yaml,.nais/${{ matrix.cluster }}/nginx.yaml
          VARS: .nais/${{ matrix.cluster }}/ingresses.yaml
          PRINT_PAYLOAD: true
