name: Build and deploy

on: [ push ]

env:
  IMAGE: ghcr.io/${{ github.repository }}:${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v3
        with:
          tags: ${{ env.IMAGE }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          docker-compose build 
          docker-compose run --volume ./reports:/reports/:rw --rm test --report-junit /reports/junit.xml
      - uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: './reports/junit.xml'

  deploy-dev:
    needs: [ build, test ]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cluster: [ dev-gcp, dev-fss ]
    steps:
      - uses: actions/checkout@v3
      - name: Prepare ConfigMap
        run: |-
          kubectl create configmap --dry-run=client -o yaml \
            --from-file .nais/${{ matrix.cluster }}/nginx.conf.d/ \
            --namespace teamdagpenger \
            dp-videresending-config \
          | kubectl label -f - --dry-run=client --local -o yaml \
            team=teamdagpenger | tee .nais/${{ matrix.cluster }}/nginx.yaml

      - uses: nais/deploy/actions/deploy@master
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: ${{ matrix.cluster }}
          RESOURCE: .nais/nais.yaml,.nais/${{ matrix.cluster }}/nginx.yaml
          VARS: .nais/${{ matrix.cluster }}/ingresses.yaml
          PRINT_PAYLOAD: true

  deploy-prod:
    needs: [ build, test ]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cluster: [ prod-gcp, prod-fss ]
    steps:
      - uses: actions/checkout@v3
      - name: Prepare ConfigMap
        run: |-
          kubectl create configmap --dry-run=client -o yaml \
            --from-file .nais/${{ matrix.cluster }}/nginx.conf.d/ \
            --namespace teamdagpenger \
            dp-videresending-config \
          | kubectl label -f - --dry-run=client --local -o yaml \
            team=teamdagpenger | tee .nais/${{ matrix.cluster }}/nginx.yaml
      - uses: nais/deploy/actions/deploy@master
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: ${{ matrix.cluster }}
          RESOURCE: .nais/nais.yaml,.nais/${{ matrix.cluster }}/nginx.yaml
          VARS: .nais/${{ matrix.cluster }}/ingresses.yaml
          PRINT_PAYLOAD: true
